"""empty message

Revision ID: 081cbc1666ae
Revises: 1ad883877cfc
Create Date: 2024-02-04 01:40:30.639139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081cbc1666ae'
down_revision = '1ad883877cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('movies_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('actors')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('actors', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('movies_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
