"""empty message

Revision ID: 81cccfc893cd
Revises: cec92c5f7808
Create Date: 2024-02-04 00:02:25.319810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cccfc893cd'
down_revision = 'cec92c5f7808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=580),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.alter_column('hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=580),
               existing_nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('release_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('user_id')

    op.drop_table('comment')
    # ### end Alembic commands ###
