"""empty message

Revision ID: cae6f568c2f8
Revises: ea4d8081103f
Create Date: 2024-01-31 03:17:47.849678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae6f568c2f8'
down_revision = 'ea4d8081103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('actors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('actors')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
